### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by sysmat** [mangstadt/biweekly#93]
using:

```
<dependency>
            <groupId>net.sf.biweekly</groupId>
            <artifactId>biweekly</artifactId>
            <version>0.6.3</version>
        </dependency>
```

in app:

```
ICalendar ical = Biweekly.parse(isc).first();
            VEvent event = ical.getEvents().get(0);
            String summary = event.getSummary().getValue();
```

ics:

```
BEGIN:VCALENDAR
PRODID:-//Inverse inc./SOGo 4.0.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Ljubljana
X-LIC-LOCATION:Europe/Ljubljana
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VTODO
UID:998-5DFA4E00-1-66D6CB80
SUMMARY:tomaž test2
DESCRIPTION:dsfdsfdsf
CLASS:PRIVATE
STATUS:NEEDS-ACTION
CATEGORIES:Issues
DTSTART;TZID=Europe/Ljubljana:20191218T170000
DUE;TZID=Europe/Ljubljana:20191218T185600
PERCENT-COMPLETE:10
CREATED:20191218T160337Z
DTSTAMP:20191218T160337Z
LAST-MODIFIED:20191218T160738Z
LOCATION:Ljubljana
END:VTODO
END:VCALENDAR

```

stack:

```
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at biweekly.util.ListMultimap$WrappedList.get(ListMultimap.java:447)
	at biweekly.component.ICalComponent$ICalComponentList.get(ICalComponent.java:758)
	at biweekly.component.ICalComponent$ICalComponentList.get(ICalComponent.java:733)

```

**Comment by mangstadt** [comment]
The ICS file doesn't have any VEVENT components. The exception is being thrown because you are calling `get(0)` on an empty list.
